# This sets a blank configuation. See:
#
# https://github.com/mojombo/jekyll/wiki/configuration
#
# For more details about configuring Jekyll.
#
exclude: [".rvmrc",".rbenv-version","Rakefile","Gemfile","Gemfile.lock","changelog.md","README.md",'sass','watch.sh','DS_Store'] # files to exclude
title: "IESF - Normandie"
# baseurl : http://iesfhautenormandie.fr/
# production_url : http://iesfhautenormandie.fr/

markdown : rdiscount

prose:
  rooturl: ''
  siteurl: "http://iesfhautenormandie.fr/"
  relativeLinks: ''
  media: 'media'
  ignore:
    - CNAME
    - robots.txt
    - index.md
    - 404.html
    - flashinfo.html
    - .gitignore
    - /_layouts
    - /_includes
    - /_plugins
    - /fonts
    - /javascripts
    - /stylesheets
    - /flash
    - /images
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "title"
        field:
          element: "text"
          label: "Ajouter un title"
          placeholder: "titre de la page"

